language: markdown
script: true
notifications:
  email:
    recipients:
    - mrjzhang@tencent.com
    on_success: always
    on_failure: always
addons:
  ssh_known_hosts: 115.159.52.227
before_install:
- openssl aes-256-cbc -K $encrypted_13f0df8b63d6_key -iv $encrypted_13f0df8b63d6_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
after_success:
- ssh ubuntu@115.159.52.227 "/usr/local/workspace/read-source-code/.travis/deploy.sh"
